id: P4740C20C
initial_creation_type: input
source_metadata:
  title: Yogasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Yoga
  data entry: Philipp A. Maas
  contribution to GRETIL: Philipp A. Maas
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:01:33.550013'
last_modified_at: '2022-03-09T15:01:33.550025'
